# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

### SHELDON INSTALLATION ###
# Check if Sheldon is installed; if not, install and source it.
if [[ -x "$(command -v sheldon)" ]]; then
    eval "$(sheldon source)"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# === core tool initialization === #
# 1. Initialize Zoxide (The shell integration script_
# This is required to define the "z" function and activate the directory tracking
eval "$(zoxide init zsh --cmd cd)"

# 2. Source local files (This contains aliases)
source $HOME/.zsh_aliases

